# Generated by Django 3.0 on 2019-12-19 13:49

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import kra.models
import utils.django.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PSRecord',
            fields=[
                ('ts', models.DateTimeField(primary_key=True, serialize=False)),
                ('hostname', models.TextField()),
                ('pid', models.BigIntegerField()),
                ('cgroup', models.TextField()),
                ('nspid', models.BigIntegerField()),
            ],
            options={
                'db_table': 'records',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Container',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('runtime_id', models.CharField(max_length=255)),
                ('memory_limit_mi', models.PositiveIntegerField(blank=True, null=True)),
                ('cpu_request_m', models.PositiveIntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Workload',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', utils.django.models.EnumField(enum_class=kra.models.WorkloadKind)),
                ('namespace', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('priority', models.FloatField(default=1, validators=[django.core.validators.MinValueValidator(0)])),
                ('auto_downgrade', models.BooleanField(default=False)),
                ('min_auto_downgrade_interval_sec', models.PositiveIntegerField(blank=True, null=True)),
            ],
            options={
                'unique_together': {('kind', 'namespace', 'name')},
            },
        ),
        migrations.CreateModel(
            name='ResourceUsage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('measured_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('memory_mi', models.PositiveIntegerField(blank=True, null=True)),
                ('cpu_m', models.PositiveIntegerField(blank=True, null=True)),
                ('cpu_m_seconds', models.BigIntegerField(blank=True, null=True)),
                ('container', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kra.Container')),
            ],
        ),
        migrations.CreateModel(
            name='Pod',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(unique=True)),
                ('namespace', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('spec_hash', models.CharField(max_length=32)),
                ('started_at', models.DateTimeField()),
                ('gone_at', models.DateTimeField(blank=True, null=True)),
                ('workload', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='kra.Workload')),
            ],
        ),
        migrations.CreateModel(
            name='OOMEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('happened_at', models.DateTimeField()),
                ('target_pid', models.BigIntegerField(blank=True, null=True)),
                ('victim_pid', models.BigIntegerField(blank=True, null=True)),
                ('target_comm', models.CharField(blank=True, max_length=32)),
                ('victim_comm', models.CharField(blank=True, max_length=32)),
                ('container', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kra.Container')),
            ],
        ),
        migrations.AddField(
            model_name='container',
            name='pod',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kra.Pod'),
        ),
        migrations.CreateModel(
            name='Adjustment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('done_at', models.DateTimeField()),
                ('pre_memory_limit_mi', models.PositiveIntegerField(blank=True, null=True)),
                ('new_memory_limit_mi', models.PositiveIntegerField(blank=True, null=True)),
                ('pre_cpu_request_m', models.PositiveIntegerField(blank=True, null=True)),
                ('new_cpu_request_m', models.PositiveIntegerField(blank=True, null=True)),
                ('workload', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kra.Workload')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='container',
            unique_together={('pod', 'name'), ('pod', 'runtime_id')},
        ),
    ]
