# Generated by Django 3.0 on 2019-12-24 19:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kra', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Investigation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('container_name', models.CharField(max_length=255)),
                ('done_at', models.DateTimeField(auto_now=True)),
                ('max_memory_mi', models.PositiveIntegerField(blank=True, null=True)),
                ('memory_limit_mi', models.PositiveIntegerField(blank=True, null=True)),
                ('avg_cpu_m', models.PositiveIntegerField(blank=True, null=True)),
                ('cpu_request_m', models.PositiveIntegerField(blank=True, null=True)),
                ('workload', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kra.Workload')),
            ],
            options={
                'unique_together': {('workload', 'container_name')},
            },
        ),
    ]
