# Generated by Django 3.0 on 2019-12-16 23:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kra', '0002_auto_20191216_2031'),
    ]

    operations = [
        migrations.RenameField(
            model_name='adjustment',
            old_name='new_cpu_request',
            new_name='new_cpu_request_m',
        ),
        migrations.RenameField(
            model_name='adjustment',
            old_name='new_memory_limit_mb',
            new_name='new_memory_limit_mi',
        ),
        migrations.RenameField(
            model_name='adjustment',
            old_name='pre_cpu_request',
            new_name='pre_cpu_request_m',
        ),
        migrations.RenameField(
            model_name='adjustment',
            old_name='pre_memory_limit_mb',
            new_name='pre_memory_limit_mi',
        ),
        migrations.RenameField(
            model_name='container',
            old_name='cpu_request',
            new_name='cpu_request_m',
        ),
        migrations.RenameField(
            model_name='container',
            old_name='memory_limit_mb',
            new_name='memory_limit_mi',
        ),
        migrations.RenameField(
            model_name='resourceusage',
            old_name='cpu',
            new_name='cpu_m',
        ),
        migrations.RenameField(
            model_name='resourceusage',
            old_name='memory_mb',
            new_name='memory_mi',
        ),
    ]
