# Generated by Django 3.0 on 2019-12-25 06:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kra', '0002_investigation'),
    ]

    operations = [
        migrations.CreateModel(
            name='Suggestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('container_name', models.CharField(max_length=255)),
                ('done_at', models.DateTimeField(auto_now=True)),
                ('new_memory_limit_mi', models.PositiveIntegerField(blank=True, null=True)),
                ('new_cpu_request_m', models.PositiveIntegerField(blank=True, null=True)),
                ('reason', models.TextField(blank=True)),
                ('priority', models.IntegerField(default=100)),
                ('workload', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kra.Workload')),
            ],
            options={
                'unique_together': {('workload', 'container_name')},
            },
        ),
    ]
