# Generated by Django 3.0 on 2019-12-17 15:30

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('kra', '0003_auto_20191216_2332'),
    ]

    operations = [
        migrations.AddField(
            model_name='resourceusage',
            name='cpu_m_seconds',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='resourceusage',
            name='measured_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
