# Generated by Django 3.0 on 2019-12-18 13:31

import random
import string
from django.db import migrations, models


def gen_container_runtime_id(length=64):
    letters = string.ascii_lowercase + string.digits
    return ''.join(random.choice(letters) for _ in range(length))


class Migration(migrations.Migration):

    dependencies = [
        ('kra', '0004_auto_20191217_1530'),
    ]

    operations = [
        migrations.AddField(
            model_name='container',
            name='runtime_id',
            field=models.CharField(default=gen_container_runtime_id, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='container',
            unique_together={('pod', 'name'), ('pod', 'runtime_id')},
        ),
    ]
