# Generated by Django 3.0 on 2020-01-09 14:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kra', '0004_summary'),
    ]

    operations = [
        migrations.AddField(
            model_name='suggestion',
            name='summary',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='kra.Summary'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='suggestion',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='suggestion',
            name='container_name',
        ),
        migrations.RemoveField(
            model_name='suggestion',
            name='workload',
        ),
    ]
