# Generated by Django 3.2.2 on 2021-05-17 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kra', '0005_suggestion_summary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='suggestion',
            name='priority',
            field=models.IntegerField(default=0),
        ),
    ]
