# Generated by Django 3.2.2 on 2021-05-17 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kra', '0006_alter_suggestion_priority'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='adjustment',
            index=models.Index(fields=['done_at'], name='kra_adjustm_done_at_522b96_idx'),
        ),
        migrations.AddIndex(
            model_name='oomevent',
            index=models.Index(fields=['happened_at'], name='kra_oomeven_happene_ec892a_idx'),
        ),
        migrations.AddIndex(
            model_name='resourceusage',
            index=models.Index(fields=['measured_at'], name='kra_resourc_measure_110b62_idx'),
        ),
    ]
