# Generated by Django 3.2.2 on 2021-05-27 12:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kra', '0007_add_time_indexes'),
    ]

    operations = [
        migrations.CreateModel(
            name='InstanceSummary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('max_memory_mi', models.PositiveIntegerField()),
                ('avg_cpu_m', models.PositiveIntegerField()),
                ('aggregated', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kra.summary')),
            ],
        ),
    ]
