# Generated by Django 3.2.2 on 2021-05-28 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kra', '0010_resourceusage_idx'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='pod',
            index=models.Index(fields=['started_at'], name='kra_pod_started_b1cc66_idx'),
        ),
    ]
