# Generated by Django 3.2.2 on 2021-05-29 22:02

from django.db import migrations, models


def copy_started_at(apps, schema_editor):
    Container = apps.get_model('kra', 'Container')
    Pod = apps.get_model('kra', 'Pod')
    schema_editor.execute(r"""
        UPDATE %(c_table)s AS c
            SET started_at = pod.started_at
        FROM %(pod_table)s AS pod
            WHERE c.pod_id = pod.id
        """ % {
        'c_table': Container._meta.db_table,
        'pod_table': Pod._meta.db_table,
    })


class Migration(migrations.Migration):

    dependencies = [
        ('kra', '0012_drop_nulls'),
    ]

    operations = [
        migrations.AddField(
            model_name='container',
            name='started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.RunPython(copy_started_at, lambda: None),
        migrations.AlterField(
            model_name='container',
            name='started_at',
            field=models.DateTimeField(),
        ),
    ]
