# Generated by Django 3.2.2 on 2021-05-30 18:48

from django.db import migrations


def fix_started_at(apps, schema_editor):
    Container = apps.get_model('kra', 'Container')
    ResourceUsage = apps.get_model('kra', 'ResourceUsage')

    schema_editor.execute(r"""
    UPDATE %(container_tblname)s AS c
        SET started_at = (
            SELECT
                min(measured_at) - interval '30 seconds'
            FROM %(ru_tblname)s
            WHERE container_id = c.id AND measured_at < c.started_at
        )
    WHERE started_at > (
        SELECT
            min(measured_at)
        FROM %(ru_tblname)s
        WHERE container_id = c.id AND measured_at < c.started_at
    )
    """ % {
        'container_tblname': Container._meta.db_table,
        'ru_tblname': ResourceUsage._meta.db_table,
    })


class Migration(migrations.Migration):

    dependencies = [
        ('kra', '0014_alter_container_unique_together'),
    ]

    operations = [
        migrations.RunPython(fix_started_at, lambda: None),
    ]
