# Generated by Django 3.2.2 on 2021-05-30 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kra', '0015_fix_container_started_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='summary',
            name='avg_memory_mi',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='summary',
            name='max_cpu_m',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='summary',
            name='stddev_cpu_m',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='summary',
            name='stddev_memory_mi',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddIndex(
            model_name='container',
            index=models.Index(fields=['started_at'], name='kra_contain_started_97fddb_idx'),
        ),
    ]
