# Generated by Django 3.2.2 on 2021-05-30 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kra', '0016_summary_all_stats'),
    ]

    operations = [
        migrations.AddField(
            model_name='instancesummary',
            name='avg_memory_mi',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='instancesummary',
            name='max_cpu_m',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='instancesummary',
            name='stddev_cpu_m',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='instancesummary',
            name='stddev_memory_mi',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
    ]
