# Generated by Django 3.2.2 on 2021-05-30 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kra', '0018_fix_container_started_at_2'),
    ]

    operations = [
        migrations.RenameField(
            model_name='suggestion',
            old_name='reason',
            new_name='memory_reason',
        ),
        migrations.AddField(
            model_name='suggestion',
            name='cpu_reason',
            field=models.TextField(blank=True),
        ),
    ]
