# Generated by Django 3.2.2 on 2021-06-04 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kra', '0019_suggestion_split_reason'),
    ]

    operations = [
        migrations.AddField(
            model_name='workload',
            name='affinity',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
