# Generated by Django 3.2.2 on 2021-06-07 13:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kra', '0020_workload_affinity'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContainerAdjustment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('container_name', models.CharField(max_length=255)),
                ('new_memory_limit_mi', models.PositiveIntegerField(blank=True, null=True)),
                ('new_cpu_request_m', models.PositiveIntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='OperationResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('finished_at', models.DateTimeField()),
                ('data', models.JSONField(blank=True, null=True)),
                ('error', models.JSONField(blank=True, null=True)),
            ],
        ),
        migrations.RemoveIndex(
            model_name='adjustment',
            name='kra_adjustm_done_at_522b96_idx',
        ),
        migrations.RenameField(
            model_name='adjustment',
            old_name='done_at',
            new_name='scheduled_for',
        ),
        migrations.RemoveField(
            model_name='adjustment',
            name='new_cpu_request_m',
        ),
        migrations.RemoveField(
            model_name='adjustment',
            name='new_memory_limit_mi',
        ),
        migrations.RemoveField(
            model_name='adjustment',
            name='pre_cpu_request_m',
        ),
        migrations.RemoveField(
            model_name='adjustment',
            name='pre_memory_limit_mi',
        ),
        migrations.AddIndex(
            model_name='adjustment',
            index=models.Index(fields=['scheduled_for'], name='kra_adjustm_schedul_a1fd28_idx'),
        ),
        migrations.AddField(
            model_name='containeradjustment',
            name='adjustment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='containers', to='kra.adjustment'),
        ),
        migrations.AddField(
            model_name='adjustment',
            name='result',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='kra.operationresult'),
        ),
    ]
