# Generated by Django 3.2.2 on 2021-06-11 22:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kra', '0021_adjustment_update'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PSRecord',
        ),
    ]
