# Generated by Django 3.2.2 on 2021-06-29 12:48

from collections import defaultdict

from django.db import migrations, models


def set_finished_at(apps, schema_editor):
    Pod = apps.get_model('kra', 'Pod')
    Container = apps.get_model('kra', 'Container')

    pods = Pod.objects.in_bulk(field_name='id')
    containers_flat = list(Container.objects.all().order_by('started_at'))
    containers_by_name_by_pod = defaultdict(lambda: defaultdict(list))

    for c in containers_flat:
        containers = containers_by_name_by_pod[c.pod_id][c.name]
        if containers:
            containers[-1].finished_at = c.started_at
        containers.append(c)

    for pod_id, containers_by_name in containers_by_name_by_pod.items():
        pod = pods[pod_id]
        for containers in containers_by_name.values():
            containers[-1].finished_at = pod.gone_at

    Container.objects.bulk_update(containers_flat, ['finished_at'], batch_size=1000)


class Migration(migrations.Migration):

    dependencies = [
        ('kra', '0022_delete_psrecord'),
    ]

    operations = [
        migrations.AddField(
            model_name='container',
            name='finished_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.RunPython(set_finished_at, migrations.RunPython.noop),
    ]
