# Generated by Django 3.2.2 on 2021-07-14 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kra', '0023_container_finished_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='oomevent',
            name='is_critical',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
