# Generated by Django 3.2.2 on 2021-07-14 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kra', '0024_oomevent_is_critical'),
    ]

    operations = [
        migrations.AddField(
            model_name='oomevent',
            name='is_ignored',
            field=models.BooleanField(default=False),
        ),
    ]
